### ISSUE TITLE
Final output image issue in inference steps

### ISSUE THREAD

**Issue by vinaysheelwagh** [DIUx-xView/xView2_baseline#12]
I was running the inference steps individually by following the inference.sh script. But finally I am getting the output as plain black image. I am using all the following steps from inference.sh with trained weights from the releases section.

1. Running the localization inference
`!python inference.py --input "/content/drive/My Drive/xview/xBD/palu-tsunami/images/palu-tsunami_00000019_pre_disaster.png" --weights "/content/drive/My Drive/xview/localization.h5" --mean "/content/drive/My Drive/xview/weights/mean.npy" --output "/content/drive/My Drive/xview/output/palu-tsunami_00000019_pre_disaster/labels/palu-tsunami_00000019_pre_disaster.json" `

2. Extracting polygon from post image
`!python process_data_inference.py --input_img "/content/drive/My Drive/xview/xBD/palu-tsunami/images/palu-tsunami_00000019_post_disaster.png" --label_path "/content/drive/My Drive/xview/output/palu-tsunami_00000019_pre_disaster/labels/palu-tsunami_00000019_pre_disaster.json" --output_dir "/content/drive/My Drive/xview/output/output_polygons" --output_csv "/content/drive/My Drive/xview/output/output.csv" `

3. Classifying extracted polygons 
`!python damage_inference.py --test_data "/content/drive/My Drive/xview/output/output_polygons" --test_csv "/content/drive/My Drive/xview/output/output.csv" --model_weights "/content/drive/My Drive/xview/classification.hdf5" --output_json "/content/drive/My Drive/xview/output/classification_inference.json" `

4. Combining the predicted polygons with the predicted label
`!python combine_jsons.py --polys "/content/drive/My Drive/xview/output/palu-tsunami_00000019_pre_disaster/labels/palu-tsunami_00000019_pre_disaster.json" --classes "/content/drive/My Drive/xview/output/classification_inference.json" --output "/content/drive/My Drive/xview/output/inference.json" `

5. Transforming the inference json file to the image required
`!python inference_image_output.py --input "/content/drive/My Drive/xview/output/inference.json" --output "/content/drive/My Drive/xview/output/image_tsunami.png" `

All of these scripts are running correctly without any warnings and error but, I am getting output as plain black image: 
![image_tsunami](https://user-images.githubusercontent.com/42643440/84139517-ef280a00-aa47-11ea-986b-6e804d19ba95.png)

Can you suggest me what is wrong in my flow or am I missing any steps?

**Comment by RitwikGupta** [comment]
The differences in the image are visually imperceptible since the pixel values are 0, 1, 2, 3, etc. @deg4uss3r will be pushing some code that we wrote to make a colored overlay. That will help you debug your output.

**Comment by deg4uss3r** [comment]
@vinaysheelwagh I added the code for the [overlay](https://github.com/DIUx-xView/xView2_baseline/tree/master/overlay_output_to_image). That should help!

**Comment by vinaysheelwagh** [comment]
Thank you so much for your prompt and quick reply. This is what I was looking for, it is working correctly and giving the desired output. Thanks again @RitwikGupta  @deg4uss3r
