### ISSUE TITLE
Question about xBD dataset

### ISSUE THREAD

**Issue by Alive1024** [DIUx-xView/xView2_baseline#15]
xBD dataset's paper says _"Furthermore, the dataset contains bounding boxes and labels for environmental factors such as fire, water, and smoke."_ But I can't find any annotations about the environment factors in those .json files. Anyone who can tell me where them are? Thanks very much.

**Comment by RitwikGupta** [comment]
That was in the "Creating xBD", WIP workshop paper. For the final release of the dataset, we removed this part of the dataset since it was overly noisy. The updated manuscript is here: https://arxiv.org/abs/1911.09296
