### ISSUE TITLE
xview_geotransforms.json

### ISSUE THREAD

**Issue by yangsiyu007** [DIUx-xView/xView2_baseline#16]
The script `utils/png_to_geotiff.py` loads a file called `xview_geotransforms.json` to convert all PNG files to geoTIFFs, which would be really useful. Has `xview_geotransforms.json` been released or can be made available?

**Comment by RitwikGupta** [comment]
I will get it to be released later next week!

**Comment by RitwikGupta** [comment]
@yangsiyu007 The link is up on the website now!
