### ISSUE TITLE
Can not Decompress xview2 dataset

### ISSUE THREAD

**Issue by IcarusFal** [DIUx-xView/xView2_baseline#22]
I've downloaded all the data and verified them, then used `cat xview2.geotiff.tgz.part-a? > xview2_geotiff.tgz` command to merge them , the merged file size is about 103Gb and when i use `tar -xvzf xview2_geotiff.tgz` or `tar xzf xview2_geotiff.tgz` comands or other tools to unpack file, i get this error, `tar.exe: Error openning archive: Unrecohnized archive format` or file damaged error ... what am i doing wronge?

**Comment by deg4uss3r** [comment]
Sounds like something may have happened with the recombining, [on the website](https://xview2.org/download-links) you should be at ~51GB and it should match the following SHA-1:

```
Recombined archive: xview2_geotiff.tgz (~51GB)
SHA1: 6eae3baddf86796c15638682a6432e3e6223cb39
```

**Comment by EugeneYuZ** [comment]
You need to remove "z" from the command. This is "tar -xvf xview2_geotiff.tgz"

**Comment by IcarusFal** [comment]
problem was i used wrong commands.

**Comment by IcarusFal** [comment]
problem was using wrong commands. as it solved I close the issue
