### ISSUE TITLE
Cannot run data_finalize.sh

### ISSUE THREAD

**Issue by nehruperumalla** [DIUx-xView/xView2_baseline#23]
I am trying to get the code and train it on my machine using README. 

I am able to split the data into disasters using split_into_disasters.py file. As the next step in the readme is localization training using spacenet. I am running the sample command given in readme by changing the path suitable for my directory, whem I run it, git bash is opening and getting closed in a second.

![image](https://github.com/DIUx-xView/xView2_baseline/assets/41884444/afbda33f-f01e-415e-b1d8-65463d07803e)

**Comment by deg4uss3r** [comment]
Thanks for your kind email and issue @nehruperumalla, I am no longer with the research team and work in a different field now; however, let's see if I can help, can you send how your `/xBD/` directory looks? 

`# tree -L 3 /xBD/` should do it.

**Comment by nehruperumalla** [comment]
Thank you for your response. This is the structure of xBD folder

![image](https://github.com/DIUx-xView/xView2_baseline/assets/41884444/f8daac31-6da5-4da5-b065-d993586f3fd3)

**Comment by deg4uss3r** [comment]
Is this a writable drive? Everything in there looks correct from the first glance; however, I don't see the `spacenet_gt` folder it should create. 

Run `data_finalize.sh` again with your systems specific options but then _immediately after_ run `# echo $?` so we can tell what code the script finished with, it might be looking for a specific program that's not on your system.

**Comment by nehruperumalla** [comment]
Yes, it is a writable drive.

I am currently working on a Windows machine with WSL installed. I ran the following command echo %ERRORLEVEL%, which is a Windows equivalent. I got code 9009 as the output.

**Comment by deg4uss3r** [comment]
Looks like [`9009`](https://www.ibm.com/support/pages/node/184239) is a Windows error stating a program doesn't exist. Do you have `bc` installed on WSL? 

> This is probably a batch (.bat, .cmd). A program called in the batch was not found, and Windows sets the %errorlevel% to 9009. Connect Direct will always return the current return code from a Run Task

**Comment by nehruperumalla** [comment]
I have installed it and again I ran the command still the same issue persists.

**Comment by deg4uss3r** [comment]
Hey @nehruperumalla I'm going to need more information to be helpful could you confirm you have the following commands accessible from the same shell you run the `data_finalize.sh` script? 

- [ ] `bc` 
- [ ] `awk`
- [ ] `/bin/ls`
- [ ] `python`
- [ ] `wc`
- [ ] `split`
- [ ] `mkdir`
- [ ] `cat`
- [ ] `cp`
- [ ] `touch`
- [ ] `mv`
- [ ] `rm`

Sorry this is a bit verbose but I do not have a Windows system and have never worked with WSL. I am guessing it might be the reference to `/bin/ls` judging from the directory state and the quick exit.

**Comment by nehruperumalla** [comment]
These commands are not working on my machine. I guess Windows/WSL is the problem. I will try to do the whole thing on a separate Linux machine and I will let you know.

**Comment by nehruperumalla** [comment]
Issue got fixed when I used linux machine. Thank you for your support.

I have raised another issue that I am facing while training spacenet model. It would be great if you could help me there.
